DROP TABLE CLIENTES;
DROP TABLE SERVICIOS;
DROP TABLE HABITACIONES;
DROP TABLE SERVICIOS_CONTRATADOS;
DROP TABLE RESERVAS;
DROP TABLE TRABAJADORES;
DROP TABLE NUMERO_RESERVA;

CREATE TABLE CLIENTES
(ID_CLIENTE VARCHAR(10) PRIMARY KEY,
 NOMBRE_CLIENTE VARCHAR(60) NOT NULL,
 TELEFONO_CLIENTE INT NOT NULL,
 EMAIL_CLIENTE VARCHAR(40));

CREATE TABLE SERVICIOS
(ID_SERVICIO VARCHAR(15) PRIMARY KEY,
 PRECIO_SERVICIO FLOAT NOT NULL,
 DURACION_SERVICIO INT NOT NULL);
 
 CREATE TABLE SERVICIOS_CONTRATADOS
(ID_RESERVA INT,
 ID_SERVICIO VARCHAR(15));
 
CREATE TABLE HABITACIONES
(ID_HABITACION INT PRIMARY KEY,
 PRECIO_HABITACION FLOAT NOT NULL,
 DISPONIBILIDAD_HABITACION INT,
 ID_CLIENTE VARCHAR(15));
 
CREATE TABLE RESERVAS
(ID_RESERVA INT PRIMARY KEY,
 ID_HABITACION INT,
 ID_CLIENTE VARCHAR(10),
 NUM_PERSONAS_RESERVA INT NOT NULL,
 NUM_NOCHES_RESERVA INT NOT NULL);
 
 CREATE TABLE TRABAJADORES
(ID_TRABAJADOR VARCHAR(10) PRIMARY KEY,
 TIPO_TRABAJADOR VARCHAR(15) NOT NULL,
 NOMBRE_TRABAJADOR VARCHAR(60) NOT NULL,
 TELEFONO_TRABAJADOR INT NOT NULL,
 EMAIL_TRABAJADOR VARCHAR(40),
 JORNADA_TRABAJADOR INT,
 ANTIGUEDAD_TRABAJADOR INT,
 ACTIVO_TRABAJADOR INT,
 IDIOMAS_TRABAJADOR VARCHAR(200));
 
 CREATE TABLE NUMERO_RESERVA
 (NUMERO_RESERVA INT);
 
INSERT INTO NUMERO_RESERVA VALUES (1);

INSERT INTO TRABAJADORES values ('admin','administrador', 'admin', 1234, 'admin', 0, 0, 0, '');

commit;